services:
    # ===================== MYSQL =====================
    book-store-mysql-db:
        image: mysql:8.0
        container_name: book-store-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_book_store
            MYSQL_USER: appuser
            MYSQL_PASSWORD: appuser
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network-book-store
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
            interval: 10s
            timeout: 5s
            retries: 5
    # ===================== REDIS =====================
    redis:
        image: redis:latest
        container_name: book-store-redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - app-network-book-store
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
    
    redis-insight:
        image: redis/redisinsight:latest
        container_name: book-store-redis-insight
        ports:
            - "5540:5540"
        networks:
            - app-network-book-store
        depends_on:
            - redis
        environment:
            - REDIS_URI=redis://redis:6379
    # ===================== KAFKA + ZOOKEEPER =====================
    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
        volumes:
            - ./zookeeper-data:/var/lib/zookeeper/data
        networks:
            - app-network-book-store

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - app-network-book-store
# ===================== SPRING BOOT (BACKEND) =====================
    backend:
        build: ./book-store-be
        container_name: book-store-be
        ports:
            - "8080:8080"
        env_file:
            - ./book-store-be/.env
        depends_on:
            book-store-mysql-db:
                condition: service_healthy
            redis:
                condition: service_started
            kafka:
                condition: service_started
        volumes:
            - ./uploads:/app/uploads
        networks:
            - app-network-book-store
# ===================== REACT FRONTEND =====================
    frontend:
        build:
            context: ./book-store-fe
            dockerfile: Dockerfile
        container_name: book-store-fe
        ports:
            - "5173:5173"
        volumes:
            - ./book-store-fe:/app
            - /app/node_modules
        command: npm run dev
        # env_file:
        #     - ./pos-fe/.env
        stdin_open: true
        tty: true
        depends_on:
            - backend
        networks:
            - app-network-book-store
volumes:
    mysql-data:
    redis-data:

networks:
    app-network-book-store:
        driver: bridge